### ISSUE TITLE
I got an error when trying to start andesite server

### ISSUE THREAD

**Issue by lunaseraphica** [natanbc/andesite-node#100]
**Describe the bug**

**To Reproduce**

**Expected behavior**
To work

**System (please complete the following information):**
 - OS: [e.g. ubuntu]: Linux
 - Andesite version: 0.20.2-all
 - Client: [e.g. my-cool-client]

**Additional context**
ERROR: [18:14:52] [main/ERROR] [Andesite]: Fatal error during initialization
java.lang.IllegalArgumentException: All Ip Blocks must have the same type for a combined block
        at com.sedmelluq.lava.extensions.youtuberotator.tools.ip.CombinedIpBlock.<init>(CombinedIpBlock.java:26)
        at com.sedmelluq.lava.extensions.youtuberotator.planner.AbstractRoutePlanner.<init>(AbstractRoutePlanner.java:43)
        at com.sedmelluq.lava.extensions.youtuberotator.planner.RotatingIpRoutePlanner.<init>(RotatingIpRoutePlanner.java:51)
        at andesite.Andesite.createRoutePlanner(Andesite.java:321)
        at andesite.Andesite.<init>(Andesite.java:129)
        at andesite.Andesite.createAndesite(Andesite.java:397)
        at andesite.Andesite.main(Andesite.java:365)

**Comment by lunaseraphica** [comment]
Can someone help me with that error or not?

**Comment by lunaseraphica** [comment]
I fixed it anyway
